config/routes.rb
SimpleAdmin::Engine.routes.draw do
  # admin lib
  get    '/'                              => "admin#index",          as: :admin
  get    '/model_index/:model_name'       => "admin#model_index",    as: :admin_model_index
  get    '/model_edit/:model_name/:id'    => "admin#model_edit",     as: :admin_model_edit
  get    '/model_new/:model_name'         => "admin#model_new",      as: :admin_model_new
  post   '/model_create/:model_name'      => "admin#create",         as: :admin_model_create
  put    '/model_edit/:model_name/:id'    => "admin#update",         as: :admin_model_update
  delete '/model_destroy/:model_name/:id' => "admin#destroy",        as: :admin_model_destroy
  get    '/extension/:name'               => "admin#extension",      as: :admin_extension
  post   '/extension_post/:name'          => "admin#extension_post", as: :admin_extension_post
end

app/controllers/simple_admin/admin_controller.rb
ActionController::Parameters.permit_all_parameters = true

class SimpleAdmin::AdminController < ApplicationController
  http_basic_authenticate_with name: SimpleAdmin.config_username, password: SimpleAdmin.config_password

  before_action :admin
  before_action :setup
  before_action :restrict

  layout "simple_admin/application"

  def index
  end

  def model_index
    @resources = @model_name.constantize.order('updated_at DESC').page(params[:page]) || []
    render :index
  end

  def model_edit
    @resource = @admin.get_resource(params[:model_name], params[:id])
  end

  def model_new
    @resource = @admin.new_resource(params[:model_name])
  end

  def update
    form_params = params[@model_name.downcase]
    @resource = @admin.get_resource(@model_name, params[:id])
    @resource.assign_attributes form_params.to_h.symbolize_keys!

    if @resource.save
      redirect_to admin_model_index_path @model_name
    else
      flash[:error] = "Could not update #{@model_name}! – #{@resource.errors.messages.to_a.join(", ")}"
      redirect_to admin_model_edit_path(@model_name, params[:id])
    end
  end

  def create
    form_params = params[@model_name.downcase]
    @resource = @admin.new_resource(@model_name)
    @resource.assign_attributes form_params.to_h.symbolize_keys!

    if @resource.save
      redirect_to admin_model_index_path @model_name
    else
      flash[:error] = "Could not create #{@model_name}! – #{@resource.errors.messages.to_a.join(", ")}"
      redirect_to admin_model_new_path @model_name
    end
  end

  def destroy
    @resource = @admin.get_resource(@model_name, params[:id])
    @resource.destroy!
    redirect_to admin_model_index_path @model_name
  end

  def extension
    @extension = @admin.extensions.find{ |e| e.constant.name == params[:name].camelize }
    @extension_instance = @extension.instantiate
    render path_to_extension_view
  end

  def extension_post
    @extension = @admin.extensions.find{ |e| e.constant.name == params[:name].camelize }
    @extension_instance = @extension.instantiate

    if params[:extension].present?
      @extension_instance.form_params = params[:extension]

      if @extension_instance.process!
        # success
        flash[:notice] = @extension_instance.flash_notice
        redirect_to admin_extension_path(params[:name])
      else
        # failure
        flash[:alert] = @extension_instance.flash_alert
        render path_to_extension_view
      end
    end
  end

  private

  def admin
    @admin = Admin.new admin_config
  end

  def setup
    @table_models = @admin.table_models
    @creatable_resources = @admin.creatable_models_whitelist
  end

  def restrict
    # make sure we only try to access what we can
    return unless params[:model_name]
    @model_name = params[:model_name]
    render(text: "Could not access that Model", status: 401) unless @table_models.map(&:name).include?(@model_name)
  end

  def admin_config
    {
      model_blacklist:                  SimpleAdmin.config_model_blacklist,
      visible_columns_blacklist:        SimpleAdmin.config_visible_columns_blacklist,
      editable_columns_blacklist:       SimpleAdmin.config_editable_columns_blacklist,
      creatable_models_whitelist:       SimpleAdmin.config_creatable_models_whitelist,
      editable_associations_whitelist:  SimpleAdmin.config_editable_associations_whitelist,
      extensions:                       SimpleAdmin.config_extensions
    }
  end

  def path_to_extension_view
    # TODO: make hardcoded path to view configurable
    "/simple_admin/extensions/#{params[:name]}"
  end
end

app/controllers/simple_admin/application_controller.rb
module SimpleAdmin
  class ApplicationController < ActionController::Base
  end
end

app/helpers/simple_admin/application_helper.rb
module SimpleAdmin
  module ApplicationHelper
  end
end

app/views/layouts/simple_admin/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= SimpleAdmin.config_site_name %></title>

  <!-- Bootstrap -->
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>

  <%= stylesheet_link_tag    "simple_admin/application", media: "all" %>
  <%= javascript_include_tag "simple_admin/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">

  <h2 class="page-header admin-header"><%= link_to SimpleAdmin.config_site_name, admin_path %></h2>

  <% if flash[:notice] %>
    <p class="alert alert-info"><%= flash[:notice] %></p>
  <% end %>

  <% if flash[:alert] %>
    <p class="alert alert-warning"><%= flash[:alert] %></p>
  <% end %>

  <div class="row">
    <div class="col-sm-4">

      <div class="row">
        <div class="col-sm-12">
          <% @table_models.each do |t_model| %>
            <a href="<%= url_for admin_model_index_path(t_model) %>" class="list-group-item <%= 'active' if t_model.name == @model_name %> ">
              <span class="badge pull-right"><%= t_model.count %></span>
              <h4 class="list-group-item-heading"><%= t_model.name %></h4>
            </a>
          <% end %>
        </div>
      </div>

      <% if @admin.extensions.any? %>
        <hr>
        <div class="row">
          <div class="col-sm-12">
            <% @admin.extensions.each do |ext| %>
              <a href="<%= url_for admin_extension_path(ext.view_name) %>" class="list-group-item <%= 'active' if ext.title == @extension.try(:title) %> ">
                <h4 class="list-group-item-heading"><%= ext.title %></h4>
              </a>
            <% end %>
          </div>
        </div>
      <% end %>

    </div>

    <div class="col-sm-8">
      <%= yield %>
    </div>

  </div>

</div>

</body>
</html>