config/routes.rb
SimpleAdmin::Engine.routes.draw do
  # admin lib
  get    '/'                              => "admin#index",          as: :admin
  get    '/model_index/:model_name'       => "admin#model_index",    as: :admin_model_index
  get    '/model_edit/:model_name/:id'    => "admin#model_edit",     as: :admin_model_edit
  get    '/model_new/:model_name'         => "admin#model_new",      as: :admin_model_new
  post   '/model_create/:model_name'      => "admin#create",         as: :admin_model_create
  put    '/model_edit/:model_name/:id'    => "admin#update",         as: :admin_model_update
  delete '/model_destroy/:model_name/:id' => "admin#destroy",        as: :admin_model_destroy
  get    '/extension/:name'               => "admin#extension",      as: :admin_extension
  post   '/extension_post/:name'          => "admin#extension_post", as: :admin_extension_post
end

app/controllers/simple_admin/admin_controller.rb
ActionController::Parameters.permit_all_parameters = true

class SimpleAdmin::AdminController < ApplicationController
  http_basic_authenticate_with name: SimpleAdmin.config_username, password: SimpleAdmin.config_password

  before_action :admin
  before_action :setup
  before_action :restrict

  layout "simple_admin/application"

  def index
  end

  def model_index
    @resources = @model_name.constantize.order('updated_at DESC').page(params[:page]) || []
    render :index
  end

  def model_edit
    @resource = @admin.get_resource(params[:model_name], params[:id])
  end

  def model_new
    @resource = @admin.new_resource(params[:model_name])
  end

  def update
    form_params = params[@model_name.downcase]
    @resource = @admin.get_resource(@model_name, params[:id])
    @resource.assign_attributes form_params.to_h.symbolize_keys!

    if @resource.save
      redirect_to admin_model_index_path @model_name
    else
      flash[:error] = "Could not update #{@model_name}! – #{@resource.errors.messages.to_a.join(", ")}"
      redirect_to admin_model_edit_path(@model_name, params[:id])
    end
  end

  def create
    form_params = params[@model_name.downcase]
    @resource = @admin.new_resource(@model_name)
    @resource.assign_attributes form_params.to_h.symbolize_keys!

    if @resource.save
      redirect_to admin_model_index_path @model_name
    else
      flash[:error] = "Could not create #{@model_name}! – #{@resource.errors.messages.to_a.join(", ")}"
      redirect_to admin_model_new_path @model_name
    end
  end

  def destroy
    @resource = @admin.get_resource(@model_name, params[:id])
    @resource.destroy!
    redirect_to admin_model_index_path @model_name
  end

  def extension
    @extension = @admin.extensions.find{ |e| e.constant.name == params[:name].camelize }
    @extension_instance = @extension.instantiate
    render path_to_extension_view
  end

  def extension_post
    @extension = @admin.extensions.find{ |e| e.constant.name == params[:name].camelize }
    @extension_instance = @extension.instantiate

    if params[:extension].present?
      @extension_instance.form_params = params[:extension]

      if @extension_instance.process!
        # success
        flash[:notice] = @extension_instance.flash_notice
        redirect_to admin_extension_path(params[:name])
      else
        # failure
        flash[:alert] = @extension_instance.flash_alert
        render path_to_extension_view
      end
    end
  end

  private

  def admin
    @admin = Admin.new admin_config
  end

  def setup
    @table_models = @admin.table_models
    @creatable_resources = @admin.creatable_models_whitelist
  end

  def restrict
    # make sure we only try to access what we can
    return unless params[:model_name]
    @model_name = params[:model_name]
    render(text: "Could not access that Model", status: 401) unless @table_models.map(&:name).include?(@model_name)
  end

  def admin_config
    {
      model_blacklist:                  SimpleAdmin.config_model_blacklist,
      visible_columns_blacklist:        SimpleAdmin.config_visible_columns_blacklist,
      editable_columns_blacklist:       SimpleAdmin.config_editable_columns_blacklist,
      creatable_models_whitelist:       SimpleAdmin.config_creatable_models_whitelist,
      editable_associations_whitelist:  SimpleAdmin.config_editable_associations_whitelist,
      extensions:                       SimpleAdmin.config_extensions
    }
  end

  def path_to_extension_view
    # TODO: make hardcoded path to view configurable
    "/simple_admin/extensions/#{params[:name]}"
  end
end

app/controllers/simple_admin/application_controller.rb
module SimpleAdmin
  class ApplicationController < ActionController::Base
  end
end

app/helpers/simple_admin/application_helper.rb
module SimpleAdmin
  module ApplicationHelper
  end
end

app/views/simple_admin/admin/_dashboard.html.erb
<table class="table table-bordered">
  <tr>
    <th>Model</td>
    <th>Count</td>
    <th>Visible</td>
    <th>Editable</td>
    <th>Reflections</td>
  </tr>
  <% @table_models.each do |tm| %>
    <tr>
      <td><%= tm.name %></td>
      <td><%= tm.count %></td>
      <td><%= @admin.visible_attributes_for_model(tm.name).join(", ") %></td>
      <td><%= @admin.editable_attributes_for_model(tm.name).join(", ") %></td>
      <td><%= tm.reflections.map{ |k, v| [k, v.class.name.demodulize].join(": ") }.join(", ") %></td>
    </tr>
  <% end %>
</table>

app/views/simple_admin/admin/index.html.erb
<% if @resources.present? %>
  <div class="panel panel-primary">
    <div class="panel-heading">
      <%= @model_name %>
      <%= @creatable_resources.include?(@model_name.constantize) ? link_to("New", admin_model_new_path(@model_name), class: "btn btn-success btn-xs") : nil %>
    </div>

    <div class="table-responsive">
      <table class="table table-striped table-bordered table-hover table-condensed">
        <thead>
          <tr>
            <% @admin.visible_attributes_for_model(@model_name.constantize).each do |col_name| %>
              <th><%= col_name %></th>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <% col_names = @admin.visible_attributes_for_model(@model_name.constantize) || [] %>
          <% @resources.each do |resource| %>
            <tr>
              <% col_names.each do |col_name| %>
                <td class="<%= @admin.decorate_column_class(col_name) %> content"><%= resource.send(col_name) %></td>
              <% end %>
              <td class="action">
                <a href="<%= url_for admin_model_edit_path(@model_name, resource.id) %>" title="Edit" class="btn btn-default btn-xs">
                  <span class="glyphicon glyphicon-pencil"></span>
                </a>
                &nbsp;
                <%= link_to admin_model_destroy_path(@model_name, resource.id), data: { confirm: "Are you sure you want to delete this?" }, method: :delete, title: "Destroy", class: "btn btn-danger btn-xs" do %>
                  <span class="glyphicon glyphicon-remove"></span>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="panel-footer text-center">
      <%= paginate @resources %>
    </div>

  </div>

  <hr>

  <pre><% @resources.each do |resource| %><%= pp "#{resource.to_json}\n\n" %><% end %></pre>
<% else %>
  <%= render partial: "dashboard" %>
<% end %>

app/views/simple_admin/admin/model_edit.html.erb
<h2>Edit <%= @model_name %></h2>

<%= simple_form_for @resource, url: admin_model_update_path(@model_name, @resource.id), method: :put, html: {class: 'form'} do |f| %>
  <%= @admin.simple_form_field f, @model_name, {country: "country_select"} %>

  <div class="form-group">
    <%= f.submit nil, class: "btn btn-primary" %>
  </div>
<% end %>

<hr>

<pre><%= @resource.inspect %></pre>

app/views/simple_admin/admin/model_new.html.erb
<h2>New <%= @model_name %></h2>

<%= simple_form_for @resource, url: admin_model_create_path(@model_name), method: :post, html: {class: 'form'} do |f| %>
  <%= @admin.simple_form_field f, @model_name, {country: "country_select"} %>
  <%= f.submit nil, class: "btn btn-primary" %>
<% end %>

<hr>

<pre><%= @resource.inspect %></pre>